Repository BlueColonySS13/BlueColonySS13, pull requests merged in 2021-04, with the labels that each got.

#21 Remaps + Tweaks
  code/datums/supplypacks/food.dm
  code/datums/supplypacks/hospitality.dm
  code/game/mecha/equipment/tools/tools.dm
  code/game/objects/structures/crates_lockers/crates.dm
  code/modules/mining/mine_turfs.dm
  code/modules/organs/subtypes/vatborn.dm
  code/modules/research/designs.dm
  code/modules/research/designs/circuits.dm
  icons/obj/storage.dmi
  maps/geminus_neue/geminus_neue-1.dmm
  maps/geminus_neue/geminus_neue-2.dmm
  maps/geminus_neue/geminus_neue-3.dmm
  maps/geminus_neue/geminus_neue-4.dmm
  maps/geminus_neue/geminus_neue_lot_areas.dm
  maps/geminus_neue/geminus_neue_lots.dm
  polaris.dme
Labels: Bugfix, Feature Tweak, Map Change, Priority: CRITICAL, Quality of Life

#23 Stuff from the To-Do List
  code/datums/supplypacks/circuits.dm
  code/datums/supplypacks/food.dm
  code/datums/supplypacks/hospitality.dm
  code/datums/supplypacks/misc.dm
  code/datums/supplypacks/robotics.dm
  code/datums/supplypacks/supplypacks.dm
  code/game/machinery/vending.dm
  code/game/objects/structures/loot_piles.dm
Labels: Feature Tweak

#24 Bug Fixes that have been tested throroughly and work
  code/controllers/subsystems/bounties.dm
  code/controllers/subsystems/jobs.dm
  code/game/machinery/bounty_machine.dm
  code/game/objects/structures/crates_lockers/closets/secure/hydroponics.dm
  code/modules/bounty/presets/mining.dm
  code/modules/client/preference_setup/general/01_basic.dm
  code/modules/mob/living/carbon/human/human.dm
  maps/geminus_neue/geminus_neue-1.dmm
  maps/geminus_neue/geminus_neue-2.dmm
  maps/geminus_neue/geminus_neue_areas.dm
Labels: Bugfix

#27 Emergency Bizlot13 Fix
  maps/geminus_neue/geminus_neue-2.dmm
  maps/geminus_neue/geminus_neue_lot_areas.dm
Labels: Priority: CRITICAL

#31 PD Map Changes from James View
  maps/geminus_neue/geminus_neue-2.dmm
  maps/geminus_neue/geminus_neue-3.dmm
Labels: Map Change

#34 Savethetreez CoP Uniform Adjustments
  icons/mob/uniform.dmi
  icons/mob/uniform_sleeves_rolled.dmi
  polaris.dme
Labels: Sprite Change

#38 Map updates
  .gitignore
  maps/geminus_neue/geminus_neue-1.dmm
  maps/geminus_neue/geminus_neue-2.dmm
Labels: Map Change

#41 Miscellaneous Fixes & Tweaks
  maps/geminus_neue/geminus_neue_lots.dm
Labels: Feature Tweak

#46 Adds a cooldown to emotes with sounds attached to them
  code/modules/mob/emote.dm
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/mob/living/silicon/robot/emote.dm
  code/modules/mob/mob_defines.dm
Labels: Feature Tweak

#47 New admin verb: Sate
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/mapping.dm
  code/modules/admin/verbs/randomverbs.dm
Labels: New Feature

#48 Adds the "aftermarket chrome" variant of Hephaestus - Athena
  code/datums/supplypacks/robotics.dm
  code/modules/organs/robolimbs.dm
  icons/mob/human_races/cyberlimbs/hephaestus/hephaestus_alt3.dmi
Labels: Sprite Change
