Repository BlueColonySS13/BlueColonySS13, pull requests merged in 2021-03, with the labels that each got.

#3 Map Changes
  .gitignore
  code/game/turfs/flooring/flooring.dm
  config/admin_ranks.txt
  icons/turf/floors.dmi
  maps/geminus_neue/geminus_neue-1.dmm
  maps/geminus_neue/geminus_neue-2.dmm
  maps/geminus_neue/geminus_neue-3.dmm
  maps/geminus_neue/geminus_neue-4.dmm
  maps/geminus_neue/geminus_neue-5.dmm
  maps/geminus_neue/turfs/neue_turfs.dm
Labels: Map Change

#7 Bug Fixes
  code/controllers/subsystems/jobs.dm
  code/game/area/areas.dm
  code/game/machinery/transportpod.dm
  code/game/machinery/vending.dm
  code/game/objects/items/weapons/id cards/station_ids.dm
  code/game/objects/structures/props/props.dm
  code/game/sound.dm
  code/modules/client/preference_setup/loadout/loadout_head.dm
  code/modules/clothing/head/soft_caps.dm
  code/modules/clothing/under/accessories/permits.dm
  code/modules/mob/_modifiers/traits.dm
  code/modules/research/designs.dm
  icons/obj/fence.dmi
Labels: Bugfix, Quality of Life

#5 Updoot
  code/datums/lots/lot.dm
  code/datums/supplypacks/business.dm
  code/datums/supplypacks/circuits.dm
  code/datums/supplypacks/clothing.dm
  code/datums/supplypacks/decoration.dm
  code/datums/supplypacks/engineering.dm
  code/datums/supplypacks/hospitality.dm
  code/datums/supplypacks/hydroponics.dm
  code/datums/supplypacks/materials.dm
  code/datums/supplypacks/medical.dm
  code/datums/supplypacks/misc.dm
  code/datums/supplypacks/munitions.dm
  code/datums/supplypacks/recreation.dm
  code/datums/supplypacks/robotics.dm
  code/datums/supplypacks/science.dm
  code/datums/supplypacks/security.dm
  code/datums/supplypacks/supply.dm
  code/game/jobs/job/civilian_chaplain.dm
  code/game/jobs/job/council.dm
  code/game/jobs/job/emergency.dm
  code/game/jobs/job/hospital.dm
  code/game/jobs/job/legal.dm
  code/game/jobs/job/nanotrasen.dm
  code/game/jobs/job/police.dm
  code/game/jobs/job/science.dm
  code/game/jobs/job/service.dm
  code/game/machinery/vending.dm
  code/game/objects/structures/props/misc.dm
  code/game/turfs/simulated/city_turfs.dm
  code/game/turfs/simulated/outdoors/dirt.dm
  code/modules/bounty/presets/leisure.dm
  code/modules/bounty/presets/mining.dm
  code/modules/bounty/presets/news.dm
  code/modules/bounty/presets/recycling.dm
  code/modules/bounty/presets/retail.dm
  code/modules/government/court/court_fees.dm
  code/modules/government/law/law_criminal.dm
  code/modules/government/law/law_major.dm
  code/modules/government/law/law_misdemeanor.dm
  code/modules/government/president/court_fees.dm
  code/modules/government/president/landlord.dm
  code/modules/government/president/medical_fees.dm
  code/modules/government/president/permits.dm
  icons/obj/vending.dmi
  maps/geminus_neue/geminus_neue-1.dmm
  maps/geminus_neue/geminus_neue-2.dmm
  maps/geminus_neue/geminus_neue-3.dmm
  maps/geminus_neue/geminus_neue-6.dmm
  maps/geminus_neue/geminus_neue_lot_areas.dm
  maps/geminus_neue/geminus_neue_lots.dm
Labels: Do Not Merge, Feature Tweak, Lore, Map Change, Work In Progress

#8 Initial Burger Allowance (Inheritance) Increase
  code/game/jobs/job/job.dm
  code/modules/client/preference_setup/general/03_background.dm
Labels: Feature Tweak

#9 Economy Pre-Release Minor Fixes & Tweaks
  code/modules/government/credit/expenses.dm
  code/modules/government/economy/_economy_procs.dm
  code/modules/persistence/persistent_economy.dm
  code/modules/persistence/persistent_inventory.dm
  polaris.dme
Labels: Feature Tweak

#18 Job Whitelisting & (Maybe) Lag Fix
  .gitignore
  config/.gitignore
  config/config.txt
  config/hardwhitelist.txt
Labels: Feature Tweak
